application-template:
  name: openid-api
  namespace: hello-world
  service:
    type: ClusterIP
    port: 80
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  replicaCount: 1
  image:
    repository: ccrawford4/openid-api
    pullPolicy: IfNotPresent
    tag: "0.0.1"
    port: 8080
  container:
    environment:
      - name: TEST_KEY
        valueFrom:
          secretKeyRef:
            name: hello-world-secret-one
            key: hello-world-test-key
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}
  ingress:
    enabled: false
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
