application-template:
  name: hello-world
  namespace: hello-world
  clusterSecretStoreName: cluster-secret-store
  service:
    type: ClusterIP
    port: 80
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  replicaCount: 1
  image:
    repository: nginxdemos/hello
    pullPolicy: IfNotPresent
    tag: "latest"
    port: 80
  container:
    environment:
      - name: TEST_KEY_2
        valueFrom:
          secretKeyRef:
            name: hello-world-cluster-secret-one
            key: hello-world-cluster-test-key
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}
  ingress:
    enabled: false
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # SECRETS
  secrets:
    - name: hello-world-secret-one
      namespace: hello-world
      secretStoreName: hello-world-secret-store
      targetName: hello-world-secret-one
      secretsKey: hello-world-test-key
      remoteRefKey: test-secret-1
  clusterSecrets:
    - name: hello-world-cluster-secret-one
      targetName: hello-world-cluster-secret-one
      secretsKey: hello-world-cluster-test-key
      remoteRefKey: test-secret-2
