application-template:
  name: hello-world
  namespace: apps
  service:
    type: ClusterIP
    port: 80
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  replicaCount: 1
  image:
    repository: nginxdemos/hello
    pullPolicy: IfNotPresent
    tag: "latest"
    port: 80
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}
  ingress:
    enabled: false
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
