namespace: mysql

# Default values for optional parameters
defaults:
  port: 3306
  image: mysql:9.0.0
  storageSize: 2Gi # These are small apps we don't need much storage
  storageClass: manual

instances:
  - name: mysql-search-app
    hostPath: /mnt/data/mysql-search-app
    clusterSecret:
      name: mysql-search-app-credentials
      targetName: mysql-search-app-credentials
      targetNamespace: search-app
      data:
        - secretKey: username
          remoteRefKey: search-app-mysql-username
        - secretKey: password
          remoteRefKey: search-app-mysql-password
        - secretKey: database
          remoteRefKey: search-app-mysql-database
