# Example values for MySQL with external secrets
# This is the recommended approach for production deployments

name: my-mysql
namespace: my-app
clusterSecretStoreName: cluster-secret-store

# MySQL image configuration
image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

# MySQL service configuration
service:
  type: ClusterIP
  port: 3306

# PersistentVolumeClaim configuration
persistence:
  enabled: true
  storageClass: ""  # Leave empty to use default storage class
  accessMode: ReadWriteOnce
  size: 20Gi

# MySQL configuration
mysql:
  # Database to create on first run
  database: "myapp"

# Secrets configuration using external-secrets.io
secrets:
  useExternalSecrets: true
  externalSecrets:
    # These keys must exist in your secret manager (e.g., Google Secret Manager)
    rootPasswordKey: my-mysql-root-password
    userPasswordKey: my-mysql-user-password
    usernameKey: my-mysql-username

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
