# Example values for MySQL with static secrets
# WARNING: This is less secure and should only be used for testing/development

name: mysql-test
namespace: mysql-test

# MySQL image configuration
image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

# MySQL service configuration
service:
  type: ClusterIP
  port: 3306

# PersistentVolumeClaim configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# MySQL configuration
mysql:
  database: "testdb"

# Static secrets (base64 encoded in Kubernetes)
# WARNING: These values are visible in the Helm release and cluster
secrets:
  useExternalSecrets: false
  static:
    rootPassword: "changeMe123!"
    username: "testuser"
    password: "testPass456!"

# Resource limits
resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
