application-template:
  name: virgo
  namespace: virgo
  clusterSecretStoreName: cluster-secret-store
  serviceAccount:
    create: true
    name: virgo
  deployments:
    - name: virgo
      replicaCount: 1
      image:
        repository: us-central1-docker.pkg.dev/home-473419/internal/virgo
        pullPolicy: IfNotPresent
        tag: "v2.1.0"
        port: 8000
      service:
        enabled: true
        port: 8000
      # initContainers:
      #   - name: init-hailo-models
      #     image: busybox:1.36
      #     imagePullPolicy: IfNotPresent
      #     command: ["/bin/sh", "-c", "mkdir -p /models/manifests"]
      #     volumeMounts:
      #       - name: hailo-ollama
      #         mountPath: /models/blob
      container:
        volumeMounts:
          - name: gcp-sa-token
            mountPath: /var/run/secrets/workload-identity-federation
          - name: hailo-ollama
            mountPath: /usr/share/hailo-ollama/models/blob
        command: ["/bin/sh", "-c", "hailo-ollama"]
      # TODO: fix the WIF issue with the virgo node so we can update this Node Selector
      nodeSelector:
        kubernetes.io/hostname: virgo
      volumes:
        - name: gcp-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: "//iam.googleapis.com/projects/631401797177/locations/global/workloadIdentityPools/home-cluster-pool/providers/home-cluster-oidc-provider"
                  expirationSeconds: 3600
                  path: token
        - name: hailo-ollama
          persistentVolumeClaim:
            claimName: hailo-ollama-pvc
  persistentVolumeClaims:
    - name: hailo-ollama
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
