{{- range .Values.instances }}
{{- if .clusterSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ .clusterSecret.name }}
spec:
  externalSecretName: {{ .clusterSecret.targetName }}

  # Select both the Redis namespace and the target namespace
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - {{ $.Values.namespace }}
          - {{ .clusterSecret.targetNamespace }}

  refreshTime: {{ .clusterSecret.refreshTime | default "1m" }}

  externalSecretSpec:
    secretStoreRef:
      name: {{ .clusterSecret.secretStore | default "gcp-secret-store" }}
      kind: {{ .clusterSecret.secretStoreKind | default "ClusterSecretStore" }}

    refreshInterval: {{ .clusterSecret.refreshInterval | default "1h" }}

    target:
      name: {{ .clusterSecret.targetName }}
      creationPolicy: {{ .clusterSecret.creationPolicy | default "Owner" }}

    data:
      {{- $clusterSecret := .clusterSecret }}
      {{- range .clusterSecret.data }}
      - secretKey: {{ .secretKey }}
        remoteRef:
          key: {{ $clusterSecret.name }}
          property: {{ .remoteRefKey }}
      {{- end }}
{{- end }}
{{- end }}
