{{- range .Values.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - image: {{ .image | default $.Values.defaults.image }}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .secretName }}
              key: password
        ports:
        - containerPort: {{ .port | default $.Values.defaults.port }}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .name }}-pv-claim
{{- end }}
