application-template:
  name: portfolio
  namespace: portfolio
  clusterSecretStoreName: cluster-secret-store
  serviceAccount:
    create: true
    name: portfolio

  deployments:
    - name: portfolio
      replicaCount: 3
      image:
        repository: ccrawford4/portfolio
        pullPolicy: IfNotPresent
        tag: "v1.0.6"
        port: 3000
      service:
        enabled: true
        port: 3000
      container:
        env:
          - name: CHAT_API_KEY
            valueFrom:
              secretKeyRef:
                name: portfolio-secrets
                key: chat-api-key
          - name: CHAT_API_URL
            value: "http://ai-agent-api.ai-agent-api.svc.cluster.local/chat"
        volumeMounts:
          - name: gcp-sa-token
            mountPath: /var/run/secrets/workload-identity-federation
      volumes:
        - name: gcp-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: "//iam.googleapis.com/projects/631401797177/locations/global/workloadIdentityPools/home-cluster-pool/providers/home-cluster-oidc-provider"
                  expirationSeconds: 3600
                  path: token

    - name: nginx
      replicaCount: 2
      serviceAccount: nginx-example
      image:
        repository: us-central1-docker.pkg.dev/home-473419/internal/nginx
        pullPolicy: Always
        tag: "latest"
        port: 80
      service:
        enabled: true
        port: 80
      container:
        volumeMounts:
          - name: gcp-sa-token
            mountPath: /var/run/secrets/workload-identity-federation
      volumes:
        - name: gcp-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: "//iam.googleapis.com/projects/631401797177/locations/global/workloadIdentityPools/home-cluster-pool/providers/home-cluster-oidc-provider"
                  expirationSeconds: 3600
                  path: token


  secrets:
    - name: portfolio-secrets
      data:
        - secretKey: chat-api-key
          remoteRefKey: portfolio-chat-api-key
