# Example values for Redis with external secrets
# This is the recommended approach for production deployments

name: my-redis
namespace: my-app
clusterSecretStoreName: cluster-secret-store

# Redis image configuration
image:
  repository: redis
  tag: "7.0"
  pullPolicy: IfNotPresent

# Redis service configuration
service:
  type: ClusterIP
  port: 6379

# PersistentVolumeClaim configuration
persistence:
  enabled: true
  storageClass: ""  # Leave empty to use default storage class
  accessMode: ReadWriteOnce
  size: 8Gi

# Secrets configuration using external-secrets.io
secrets:
  useExternalSecrets: true
  externalSecrets:
    passwordKey: search-app-redis-password

# Resource limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
