# Tasks
tasks:
  - name: hello-task
    stepTemplate:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    steps:
      - name: echo
        image: alpine
        script: |
          #/bin/sh
          echo "Hello!"
  - name: goodbye-task
    stepTemplate:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
    params:
      - name: username
        type: string
    steps:
      - name: echo
        image: alpine
        script: |
          #/bin/sh
          echo "Goodbye, $(params.username)!"
# Pipelines
pipelines:
  - name: hello-pipeline
    params:
      - name: username
        type: string
    tasks:
      - name: hello-task
        taskRef: hello-task
      - name: goodbye-task
        taskRef: goodbye-task
        runAfter:
          - hello-task
        params:
          - name: username
            value: $(params.username)
# PipelineRuns
pipelineRuns:
  - name: hello-pipeline-run
    pipelineRef: hello-pipeline
    params:
      - name: username
        value: "Tekton Test 1"
    podTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
  - name: hello-goodbye-pipeline-run
    pipelineRef: hello-pipeline
    params:
      - name: username
        value: "Tekton Test 2"
    podTemplate:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
