apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: nginx-ingress
    version: 2.3.0
    repository: "oci://ghcr.io/nginx/charts/nginx-ingress"
