{{- range .Values.pipelines }}
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
{{- if .params }}
  params:
    {{- range .params }}
    - name: {{ .name }}
      {{- with .type }}
      type: {{ . }}
      {{- end }}
    {{- end }}
{{- end }}
{{- if .workspaces }}
  workspaces:
    {{- range .workspaces }}
    - name: {{ .name }}
      {{- with .description }}
      description: {{ . | quote }}
      {{- end }}
    {{- end }}
{{- end }}
  tasks:
    {{- range .tasks }}
    - name: {{ .name }}
      taskRef:
        {{- if kindIs "map" .taskRef }}
{{- toYaml .taskRef | nindent 8 }}
        {{- else }}
        name: {{ .taskRef }}
        {{- end }}
      {{- if .params }}
      params:
        {{- range .params }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
      {{- end }}
      {{- if .workspaces }}
      workspaces:
        {{- range .workspaces }}
        - name: {{ .name }}
          {{- with .workspace }}
          workspace: {{ . }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
