{{- range .Values.tasks }}
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
  params:
    {{- range .params }}
    - name: {{ .name }}
      type: {{ .type }}
    {{- end }}
  tasks:
    {{- range .tasks }}
    - name: {{ .name }}
      taskRef:
        name: {{ .taskRef }}
      params:
        {{- range .params }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
    {{- end }}
{{- end }}
