{{- range .Values.pipelineRuns }}
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: {{ .pipelineRef }}
{{- if .params }}
  params:
{{- range .params }}
    - name: {{ .name }}
      value: {{ .value }}
{{- end }}
{{- if .podTemplate }}
  taskRunTemplate:
    podTemplate:
      {{- if .podTemplate.securityContext }}
      securityContext:
        {{- if .podTemplate.securityContext.allowPrivilegeEscalation }}
        allowPrivilegeEscalation: {{ .podTemplate.securityContext.allowPrivilegeEscalation }}
        {{- end }}
        {{- if .podTemplate.securityContext.runAsNonRoot }}
        runAsNonRoot: {{ .podTemplate.securityContext.runAsNonRoot }}
        {{- end }}
        {{- if .podTemplate.securityContext.runAsUser }}
        runAsUser: {{ .podTemplate.securityContext.runAsUser }}
        {{- end }}
        # {{- if .podTemplate.securityContext.capabilities }}
        # capabilities:
        #   drop:
        #   {{- range .podTemplate.securityContext.capabilities.drop }}
        #     - {{ . }}
        #   {{- end }}
        # {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
