{{- range .Values.pipelineRuns }}
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: {{ .pipelineRef }}
{{- if .params }}
  params:
{{- range .params }}
    - name: {{ .name }}
      value: {{ .value }}
{{- end }}
{{- if .workspaces }}
  workspaces:
    {{- range .workspaces }}
    - name: {{ .name }}
      {{- if .emptyDir }}
      emptyDir: {{ .emptyDir }}
      {{- end }}
      {{- if .persistentVolumeClaim }}
      persistentVolumeClaim:
{{ toYaml .persistentVolumeClaim | nindent 8 }}
      {{- end }}
      {{- if .volumeClaimTemplate }}
      volumeClaimTemplate:
{{ toYaml .volumeClaimTemplate | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
{{- if .podTemplate }}
  taskRunTemplate:
    podTemplate:
      {{- if .podTemplate.securityContext }}
      securityContext:
{{- toYaml .podTemplate.securityContext | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
