{{- range .Values.pipelineRuns }}
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: {{ .pipelineRef }}
{{- if .params }}
  params:
{{- range .params }}
    - name: {{ .name }}
      value: {{ .value }}
{{- end }}
{{- end }}
{{- end }}
