{{- with .Values.secretsConfig }}
{{- if .secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .secretStoreRef.name }}
  namespace: {{ $.Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: {{ .secretStore.projectID | quote }}
      auth:
        workloadIdentityFederation:
          audience: {{ .secretStore.audience | quote }}
          serviceAccountRef:
            name: {{ .secretStore.serviceAccount }}
            audiences:
              - {{ .secretStore.audience | quote }}
{{- end }}
{{- end }}
