{{- range .Values.tasks }}
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: {{ .name }}
  namespace: tekton-pipelines
spec:
{{- if .stepTemplate }}
  stepTemplate:
    {{- toYaml .stepTemplate | nindent 4 }}
{{- end }}
{{- if .params }}
  params:
    {{- range .params }}
    - name: {{ .name }}
      type: {{ .type }}
    {{- end }}
{{- end }}
  steps:
    {{- range .steps }}
    - name: {{ .name }}
      image: {{ .image }}
      script: |
{{ .script | indent 10 }}
    {{- end }}
{{- end }}
