{{- range .Values.clusterSecretStores }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .secretName }}
            key: {{ .secretKey }}
{{- end }}
