{{- range .Values.secretStores }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  provider:
    gcpsm:
      projectID: "home-473419"
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .secretName }}
            key: {{ .secretKey }}
{{- end }}
