{{- range .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  {{- if .googleServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .googleServiceAccount }}@home-473419.iam.gserviceaccount.com"
  {{- end }}
{{- end }}
