apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git # URL of your Git repository
    targetRevision: HEAD # Or a specific branch/tag/commit
    path: charts/my-chart # Path to your Helm chart within the repository
    helm:
      valueFiles:
        - values.yaml # Optional: specify a values file
      parameters:
        - name: replicaCount # Optional: override chart values
          value: "3"
  destination:
    server: https://kubernetes.default.svc # Your Kubernetes cluster API server
    namespace: my-app-namespace # The namespace where the application will be deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Optional: automatically create the namespace if it doesn't exist
