apiVersion: v1
kind: Secret
namespace: {{ template "pipelines.namespace" . }}
metadata:
  name: {{ template "pipelines.fullname" . }}
  labels:
    {{- include "pipelines.baseLabels" . | nindent 4 }}
    {{- include "pipelines.helmLabels" . | nindent 4 }}
    {{- include "pipelines.componentLabels" "webhook" | nindent 4 }}
