{{- if .Values.secrets.useExternalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}-secrets
    creationPolicy: Owner
  data:
  - secretKey: REDIS_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .Values.secrets.externalSecrets.passwordKey }}
      metadataPolicy: None
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.secrets.static.password | b64enc | quote }}
{{- end }}
