{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
data:
  {{- with .data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
