{{- range $key, $deployment := .Values.deployments }}
{{- if $deployment.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $deployment.name }}
  labels:
    {{- include "application-template.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $deployment.name }}
  minReplicas: {{ $deployment.autoscaling.minReplicas }}
  maxReplicas: {{ $deployment.autoscaling.maxReplicas }}
  metrics:
    {{- if $deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
