{{- range .Values.secrets }}
{{- if .staticData }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  {{ .staticData.key }}: {{ .staticData.value | b64enc | quote }}
{{- else if .data }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetName | default .name }}
    creationPolicy: Owner
  data:
  {{- range .data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .remoteRefKey }}
      metadataPolicy: None
  {{- end }}
{{- end }}
{{- end }}
