{{- range .Values.secrets }}
{{- if .data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  {{ .data.key }}: {{ .data.value | b64enc | quote }}
{{- else }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ $.Values.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .targetName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .secretsKey }}
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ .remoteRefKey }}
      metadataPolicy: None
{{- end }}
{{- end }}
