{{- if .Values.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreRef.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secretStore.projectID | quote }}
      auth:
        workloadIdentityFederation:
          audience: {{ .Values.secretStore.audience | quote }}
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccount | default .Values.serviceAccount.name | default .Values.name }}
            audiences:
              - {{ .Values.secretStore.audience | quote }}
{{- end }}
