apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{- include "application-template.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application-template.selectorLabels" . | nindent 4 }}
