{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if .Values.serviceAccount.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRole.name | default .Values.name }}
  {{- with .Values.serviceAccount.clusterRole.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.serviceAccount.clusterRole.rules | nindent 2 }}
{{- end }}
{{- if .Values.serviceAccount.clusterRoleBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.clusterRoleBinding.name | default .Values.name }}
  {{- with .Values.serviceAccount.clusterRoleBinding.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRoleBinding.roleName | default .Values.serviceAccount.clusterRole.name | default .Values.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}