namespaces:
  search-app:
    rules:
      - host: search.calum.sh
        paths:
          - path: /
            pathType: Prefix
            serviceName: search-app-frontend
            servicePort: 3000
  argocd:
    rules:
      - host: argocd.calum.sh
        paths:
          - path: /
            pathType: Prefix
            serviceName: argocd-server
            servicePort: 80

  portfolio:
    rules:
      - host: about.calum.sh
        paths:
          - path: /
            pathType: Prefix
            serviceName: portfolio
            servicePort: 3000

  openid-server:
    rules:
      - host: openid.calum.sh
        paths:
          - path: /
            pathType: Prefix
            serviceName: openid-server
            servicePort: 80
