namespace: redis

# Default values for optional parameters
defaults:
  port: 6379
  image: redis:8.2
  storageSize: 2Gi # These are small apps we don't need much storage
  storageClass: manual

instances:
  - name: redis-search-app
    hostPath: /mnt/data/redis-search-app
    clusterSecret:
      name: redis-search-app-credentials
      targetName: redis-search-app-credentials
      targetNamespace: search-app
      data:
        - secretKey: password
          remoteRefKey: search-app-redis-password
