{{- if .Values.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStoreRef.name }}
  namespace: {{ include "atlantis.namespace" . }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secretStore.projectID | quote }}
      auth:
        workloadIdentityFederation:
          audience: {{ .Values.secretStore.audience | quote }}
          serviceAccountRef:
            name: {{ template "atlantis.serviceAccountName" . }}
            audiences:
              - {{ .Values.secretStore.audience | quote }}
{{- end }}
