apiVersion: v1
appVersion: v0.14.0
description: |
  This chart bootstraps installation of [tekton pipeline](https://github.com/tektoncd/pipeline).
home: https://github.com/tektoncd/pipeline
icon: https://tekton.dev/images/tekton-horizontal-color.png
keywords:
  - helm
  - tekton
  - tektoncd
  - pipeline
  - pipelines
maintainers:
  - email: ceb@agriconomie.com
    name: eddycharly
name: pipelines
version: 0.14.0
